#  reference: https://www.appveyor.com/docs/appveyor-yml/

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

version: 1.0.2.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true


# branches to build 
branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: c:\projects\fullnode

configuration:
- Debug
- Release

# build cache to preserve files/folders between builds
cache:
  - '%USERPROFILE%\.nuget\packages'
  
init:
- ps: dotnet --info

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
- ps: |
      if($env:configuration -eq 'Debug')
      {
        git submodule update --recursive --init
        cd StratisBitcoinFullNode/src
        Write-Host "STARTED dotnet build" -foregroundcolor "magenta"
        dotnet build -c -v m 
        Write-Host "FINISHED dotnet build" -foregroundcolor "magenta"
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }

# scripts to run after build
after_build:
- ps: |
    
test_script:
- ps: |
      if($env:configuration -eq 'Debug')
      {
        Write-Host "STARTED dotnet test" -foregroundcolor "magenta"
        cd $env:APPVEYOR_BUILD_FOLDER/StratisBitcoinFullNode/src
        
        $anyFailures = $FALSE;
        Push-Location 'Stratis.Bitcoin.IntegrationTests'
        dotnet test -c --no-build
        if ($LastExitCode -ne 0) { 
          $anyFailures = $TRUE
          Add-AppveyorMessage -Message "Some tests failed in IntegrationTests."
        }
        Pop-Location

        Write-Host "FINISHED dotnet test" -foregroundcolor "magenta"
        if ($anyFailures -eq $TRUE) { $host.SetShouldExit(1) }
      }

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# pushing all files in build directory recursively
artifacts:
- path: nuget\*.nupkg
  name: nuget packages
